version: '3.4'
services:

  your-frontend:
    build: ./
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      NODE_ENV: development
      SESSION_CACHE_ENGINE: memory
    networks:
      - app-network

  # your-backend:
  #   image: defradigital/your-backend:${YOUR_BACKEND_VERSION:-latest}
  #   ports:
  #     - '3555:3555'
  #   links:
  #     - 'mongodb:mongodb'
  #   depends_on:
  #     mongodb:
  #       condition: service_started
  #   environment:
  #     PORT: 3555
  #     NODE_ENV: development
  #   networks:
  #     - app-network

################################################################################

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
