services:
  service:
    build:
      context: ../..
    container_name: cdp-node-frontend-template
    networks:
      - cdp-network
    ports:
      - "8085:8085"
    environment:
      PORT: 8085
      SESSION_CACHE_ENGINE: memory
      LOG_LEVEL: debug
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    healthcheck:
      test: curl http://localhost:8085/health
      start_period: 1s
      interval: 2s
      timeout: 30s

networks:
  cdp-network:
    driver: bridge
